### ISSUE TITLE
Which data from calib_results.txt should be used?

### ISSUE THREAD

**Issue by shadow1runner** [uzh-rpg/rpg_blender_omni_camera#1]
Hi,

first of all thank you for that plugin. 
This is more a question than a bug, but I hope someone can help me.
I've built it successfully according to your wiki and now I've calibrated a real dioptric camera, giving me the following `calib_results.txt`:

```
#polynomial coefficients for the DIRECT mapping function (ocam_model.ss in MATLAB). These are used by cam2world

5 -2.736690e+02 0.000000e+00 1.491215e-03 -1.810410e-06 6.614668e-09 

#polynomial coefficients for the inverse mapping function (ocam_model.invpol in MATLAB). These are used by world2cam

10 390.641079 204.159602 -11.846278 36.007709 17.104646 38.577696 89.296165 75.701556 27.648260 3.714537 

#center: "row" and "column", starting from 0 (C convention)

171.302880 365.152978

#affine parameters "c", "d", "e"

0.884024 0.025906 -0.027663

#image size: "height" and "width"

480 720
```

So as a next step I tried configuring the omnidirectional camera in blender.
You write

> Polynomial: a0, a1, a2, a3, a4, a5 correspond to the polynomial backward projection function parameters  in increasing degree order)

So this is how I've configured the camera:
![image](https://cloud.githubusercontent.com/assets/3902045/17833564/3eb928b0-6721-11e6-8dfd-7f82a9ea9a85.png)
i.e. using the first line

> # polynomial coefficients for the DIRECT mapping function (ocam_model.ss in MATLAB). These are used by cam2world
> 
> 5 -2.736690e+02 0.000000e+00 1.491215e-03 -1.810410e-06 6.614668e-09 

and the affine parameters

> # affine parameters "c", "d", "e"
> 
> 0.884024 0.025906 -0.027663

However it delivers weird results, e.g.:
![vlcsnap-2016-08-20-22h01m00s520](https://cloud.githubusercontent.com/assets/3902045/17833591/aa64aeb8-6721-11e6-9087-6dbf05925356.png)

While the perspective rendering looks like
![vlcsnap-2016-08-20-22h04m45s452](https://cloud.githubusercontent.com/assets/3902045/17833612/20afd7a0-6722-11e6-9043-d710cbc0d7a9.png)

And if I use your parameters for a fisheye camera it looks ok as well:
![vlcsnap-2016-08-20-22h25m29s255](https://cloud.githubusercontent.com/assets/3902045/17833705/88b39dfc-6725-11e6-8ed8-bd6e4594cd27.png)

I've also tried the second line in `calib_results.txt`, delivering no scene whatsoever.

So here my question:
Have I configured it correctly? Or do you have any hints what I might be doing wrong? Maybe it's the higher order polynoms that make the difference, that would be plausible for me.

Sorry for the long post and thanks for your help.

**Comment by shadow1runner** [comment]
@supitalp maybe you can help me on this? Sorry for bothering, but it would be a very nice add-on to generate ground truth data, thanks in advance.

**Comment by supitalp** [comment]
Dear @shadow1runner,
In the output of the camera calibration toolbox : "5 -2.736690e+02 0.000000e+00 1.491215e-03 -1.810410e-06 6.614668e-09", you should omit the first number (5 here): it simply corresponds to the order of the forward projection polynomial. In this case, the parameters should be:

a0 = -2.736690e+02
a1 = 0.000000e+00
a2 = 1.491215e-03
a3 = -1.810410e-06
a4 = 6.614668e-09

On my computer, these parameters produce an image that looks correct :)

By the way, it seems that your vertical center shift value (171.302880 px) is very odd (usually, it should be close to width / 2 = 480 / 2 = 240 px in your case)? You might want to double-check your camera calibration is correct.

Let me know if any more questions arise.

**Comment by shadow1runner** [comment]
Thank you very much @supitalp, the rendering now looks fine for me as well and sorry for that stupid question, I could have checked where that 5 comes from from the source code myself instead of bothering you. Now I only have to check why the rendering does not cover more of the screen, the resolution is set properly to 720x480, but I guess it's just a small zoom setting or such.
![untitled](https://cloud.githubusercontent.com/assets/3902045/18045425/0aa91310-6dd3-11e6-97a4-8b8930c85897.jpg)

> By the way, it seems that your vertical center shift value (171.302880 px) is very odd (usually, it should be close to width / 2 = 480 / 2 = 240 px in your case)? You might want to double-check your camera calibration is correct.

yeah, the lens is not aligned with the camera sensor (cheap camera from University..., lens is ok), that's the reason for the huge offset, a sample calibration frame looks as follows:

![la3_10](https://cloud.githubusercontent.com/assets/3902045/18045185/e200ca58-6dd1-11e6-89ff-00b451fa4520.jpg)

> Let me know if any more questions arise.

There is one, actually: Have you got a paper I should cite if I use this add-on?

Thank you very much and regards to Zurich from Innsbruck ;)

**Comment by supitalp** [comment]
Hi @shadow1runner,

> the rendering now looks fine for me as well

Good to hear :)

> Now I only have to check why the rendering does not cover more of the screen, the resolution is set properly to 720x480, but I guess it's just a small zoom setting or such.

To make the rendering cover the whole screen, you simply need to set the "Radius" parameter to a very high value (100.0 for example).

> yeah, the lens is not aligned with the camera sensor (cheap camera from University..., lens is ok), that's the reason for the huge offset, a sample calibration frame looks as follows:

OK. Be careful with the center shift values (X,Y): they do not encode the absolute image center coordinates in pixels, but the relative one.

If (cX, cY) is the absolute projection of the lens center, then X = 0.5 x image_width - cX and Y = 0.5 x image_height - cY .
In your case:
  X = 0.5 x 720 - 365.152978 = -5.15 px
  Y = 0.5 x 240 - 171.302880 = -51.3 px

Although from the image above it seems you already have set it correctly since the circle is centered at the correct position :)

> There is one, actually: Have you got a paper I should cite if I use this add-on?

Yes, please cite the following:

Z. Zhang, H. Rebecq, C. Forster, D. Scaramuzza
Benefit of Large Field-of-View Cameras for Visual Odometry
IEEE International Conference on Robotics and Automation (ICRA), 
Stockholm, 2016.

All the best for your experiments and regards to Innsbruck!

**Comment by shadow1runner** [comment]
Perfect, works like a charm!
Thank you very much, it almost resembles my real dioptric lense now :)

![untitled](https://cloud.githubusercontent.com/assets/3902045/18048134/ba6aac48-6de0-11e6-8d56-84c3ff06b785.jpg)
